web-app/src/Entity/User.php
<?php
declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Validator\Constraints\NotNull;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table('`users`')]
#[UniqueEntity(fields: ['email', 'surname', 'firstname'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    private const GROUPS = ['users'];
    private const GROUPS_TWO = ['users', 'dataByIdUser'];
    private const GROUPS_THREE = ['users', 'user', 'dataByIdUser'];

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "CUSTOM")]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    #[ORM\Column(type: "uuid", unique: true)]
    #[NotNull, Groups(self::GROUPS_THREE)]
    private ?string $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[NotNull, Groups(self::GROUPS_THREE)]
    private ?string $email = null;

    #[ORM\Column]
    #[NotNull, Groups(self::GROUPS_TWO)]
    private array $roles = [];

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(self::GROUPS_TWO)]
    private ?string $comment = null;

    #[ORM\Column]
    #[Groups(self::GROUPS)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    #[Groups(self::GROUPS)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(length: 255)]
    #[Groups(self::GROUPS)]
    private ?string $createdFrom = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(self::GROUPS)]
    private ?string $updatedFrom = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[NotNull]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    #[NotNull, Groups(self::GROUPS_THREE)]
    private ?string $surname = null;

    #[ORM\Column(length: 100)]
    #[NotNull, Groups(self::GROUPS_THREE)]
    private ?string $firstname = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    #[NotNull, Groups(self::GROUPS_TWO), MaxDepth(1)]
    private ?FederalState $federalState = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    #[NotNull, Groups(self::GROUPS_TWO), MaxDepth(1)]
    private ?Department $department = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(self::GROUPS)]
    private ?\DateTimeInterface $lastLogin = null;

    #[ORM\Column(nullable: true)]
    #[Groups(self::GROUPS_TWO)]
    private ?array $myAlertAddresses = null;

    #[ORM\Column(options: ["default" => true])]
    #[Groups(self::GROUPS_TWO)]
    private ?bool $isVisibility = null;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedFrom(): ?string
    {
        return $this->createdFrom;
    }

    public function setCreatedFrom(string $createdFrom): static
    {
        $this->createdFrom = $createdFrom;

        return $this;
    }

    public function getUpdatedFrom(): ?string
    {
        return $this->updatedFrom;
    }

    public function setUpdatedFrom(?string $updatedFrom): static
    {
        $this->updatedFrom = $updatedFrom;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname ?: "Nicht gesetzt";
    }

    public function setSurname(string $surname): static
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname ?: "Nicht gesetzt";
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFederalState(): ?FederalState
    {
        return $this->federalState;
    }

    public function setFederalState(?FederalState $federalState): static
    {
        $this->federalState = $federalState;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): static
    {
        $this->department = $department;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    public function setLastLogin(?\DateTimeInterface $lastLogin): static
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    public function getMyAlertAddresses(): ?array
    {
        return $this->myAlertAddresses;
    }

    public function setMyAlertAddresses(?array $myAlertAddresses): static
    {
        $this->myAlertAddresses = $myAlertAddresses;

        return $this;
    }

    public function isLoggedIn(): bool
    {
        if ($this->getId()) {
            return true;
        }

        return false;
    }

    public function isIsVisibility(): ?bool
    {
        return $this->isVisibility;
    }

    public function setIsVisibility(bool $isVisibility): static
    {
        $this->isVisibility = $isVisibility;

        return $this;
    }
}

web-app/src/Controller/MainController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use App\Repository\UserRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;


class MainController extends AbstractController
{
    #[Route('/', name: 'default-app')]
    public function loginRedirectToRoute(LoggerInterface $logger): RedirectResponse
    {
        $logger->info('Redirect to Web-Anwendung');

        return new RedirectResponse('/dashboard');
    }

    #[Route('/{route}', name: 'app-frontend', requirements: ['route' => '^(?!.*_wdt|_profiler|basic|api|incoming-alert-from-bosmon).+'])]
    public function index(TranslatorInterface $translator, UserRepository $userRepository, EntityManagerInterface $entityManager, LoggerInterface $logger): Response
    {

//        $pdf->generate("https://127.0.0.1:8000/operation-area/operation-report/details/bc03da3e-d2f9-409f-9817-066bd97fd865", "google.pdf");


        // Ist der Nutzer erfolgreich angemeldet, dann das letzte Anmelde DateTime setzen
        if ($this->getUser()) {
            $user = $userRepository->findOneBy(['email' => $this->getUser()->getUserIdentifier()]);
            if ($user) {
                $user->setLastLogin(new DateTime());
                $entityManager->persist($user);
                $entityManager->flush();
            }


            $logger->info('Update the Lastlogin from the User (' . $user->getUserIdentifier() . ') in der Database.');
        }

        // Weiterleitung zur Hauptseite (VUE JS)
        return $this->render('main/index.html.twig');
    }


    #[Route('/login', name: 'app-frontend-login')]
    public function toLogin(LoggerInterface $logger): Response
    {

        $logger->info('Login in the Web-Application');

        // Ist der Nutzer bereits angemeldet, dann leite ihn weiter
        if ($this->getUser()) {
            return $this->redirectToRoute('app-frontend', ['route' => 'dashboard']);
        }

        // Weiterleitung zur Hauptseite (VUE JS)
        return $this->render('main/index.html.twig');
    }

}

web-app/templates/main/api.html.twig
<script>
    const __API__ = {
        federalstates: {{ path('api_federal_states')|json_encode|raw }},
        federalstate: {
            getForDropdown: {{ path('api_federal_state_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_federal_state_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_federal_state_new')|json_encode|raw }},
            edit: {{ path('api_federal_state_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_federal_state_delete', { 'id': ' ' })|json_encode|raw }}
        },
        departments: {{ path('api_departments')|json_encode|raw }},
        department: {
            getForDropdown: {{ path('api_department_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_department_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_department_new')|json_encode|raw }},
            edit: {{ path('api_department_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_department_delete', { 'id': ' ' })|json_encode|raw }}
        },
        versions: {{ path('api_versions')|json_encode|raw }},
        version: {
            getById: {{ path('api_version_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_version_new')|json_encode|raw }},
            edit: {{ path('api_version_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_version_delete', { 'id': ' ' })|json_encode|raw }}
        },
        userRoles: {{ path('api_user_roles')|json_encode|raw }},
        userRole: {
            getForDropdown: {{ path('api_user_role_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_user_role_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_user_role_new')|json_encode|raw }},
            edit: {{ path('api_user_role_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_user_role_delete', { 'id': ' ' })|json_encode|raw }}
        },
        memberFunctions: {{ path('api_member_functions')|json_encode|raw }},
        memberFunction: {
            getForDropdown: {{ path('api_member_function_get_for_dropdown')|json_encode|raw }},
            getForDropdownOperationReport: {{ path('api_member_function_get_for_dropdown_operation_report')|json_encode|raw }},
            getById: {{ path('api_member_function_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_member_function_new')|json_encode|raw }},
            edit: {{ path('api_member_function_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_member_function_delete', { 'id': ' ' })|json_encode|raw }}
        },
        operationTypeCategories: {{ path('api_operation_type_categories')|json_encode|raw }},
        operationTypeCategory: {
            getForDropdown: {{ path('api_operation_type_category_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_operation_type_category_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_operation_type_category_new')|json_encode|raw }},
            edit: {{ path('api_operation_type_category_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_operation_type_category_delete', { 'id': ' ' })|json_encode|raw }}
        },
        operationTypes: {{ path('api_operation_types')|json_encode|raw }},
        operationType: {
            getForDropdown: {{ path('api_operation_type_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_operation_type_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_operation_type_new')|json_encode|raw }},
            edit: {{ path('api_operation_type_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_operation_type_delete', { 'id': ' ' })|json_encode|raw }}
        },
        vehicles: {{ path('api_vehicles')|json_encode|raw }},
        vehicle: {
            getOnlyDepartment: {{ path('api_vehicle_get_only_department')|json_encode|raw }},
            getForDropdown: {{ path('api_vehicle_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_vehicle_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_vehicle_new')|json_encode|raw }},
            edit: {{ path('api_vehicle_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_vehicle_delete', { 'id': ' ' })|json_encode|raw }}
        },
        toolCategories: {{ path('api_tool_categories')|json_encode|raw }},
        toolCategory: {
            getForDropdown: {{ path('api_tool_category_get_for_dropdown')|json_encode|raw }},
            getForOperationReport: {{ path('api_tool_categor_get_for_operation_report')|json_encode|raw }},
            getById: {{ path('api_tool_category_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_tool_category_new')|json_encode|raw }},
            edit: {{ path('api_tool_category_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_tool_category_delete', { 'id': ' ' })|json_encode|raw }}
        },
        tools: {{ path('api_tools')|json_encode|raw }},
        tool: {
            getForDropdown: {{ path('api_tool_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_tool_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_tool_new')|json_encode|raw }},
            edit: {{ path('api_tool_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_tool_delete', { 'id': ' ' })|json_encode|raw }}
        },
        alertAddresses: {{ path('api_alert_addresss')|json_encode|raw }},
        alertAddress: {
            getForDropdown: {{ path('api_alert_address_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_alert_address_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_alert_address_new')|json_encode|raw }},
            edit: {{ path('api_alert_address_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_alert_address_delete', { 'id': ' ' })|json_encode|raw }}
        },
        members: {{ path('api_members')|json_encode|raw }},
        member: {
            getOnlyDepartment: {{ path('api_member_get_only_department')|json_encode|raw }},
            getForDropdown: {{ path('api_member_get_for_dropdown')|json_encode|raw }},
            getById: {{ path('api_member_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            getByMemberFunction: {{ path('api_member_get_by_member_function',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_member_new')|json_encode|raw }},
            edit: {{ path('api_member_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_member_delete', { 'id': ' ' })|json_encode|raw }}
        },
        users: {{ path('api_users')|json_encode|raw }},
        user: {
            getById: {{ path('api_user_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_user_new')|json_encode|raw }},
            edit: {{ path('api_user_edit',  { 'id': ' ' })|json_encode|raw }},
            editPassword: {{ path('api_user_edit_password',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_user_delete', { 'id': ' ' })|json_encode|raw }}
        },
        generals: {{ path('api_generals')|json_encode|raw }},
        general: {
            getById: {{ path('api_general_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_general_new')|json_encode|raw }},
            edit: {{ path('api_general_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_general_delete', { 'id': ' ' })|json_encode|raw }}
        },
        incomingAlertEvaluation: {
            getChartByYear: {{ path('api_incoming_alerts_get_chart_by_year',  { 'year': ' ' })|json_encode|raw }}
        },
        incomingAlerts: {{ path('api_incoming_alerts')|json_encode|raw }},
        incomingAlertsUserRics: {{ path('api_incoming_alerts_user_rics')|json_encode|raw }},
        incomingAlertsUserRicsForOperationReport: {{ path('api_incoming_alerts_user_rics_for_operation_report')|json_encode|raw }},
        incomingAlert: {
            getById: {{ path('api_incoming_alert_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_incoming_alert_new')|json_encode|raw }},
            edit: {{ path('api_incoming_alert_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_incoming_alert_delete', { 'id': ' ' })|json_encode|raw }}
        },
        operationReports: {{ path('api_operation_reports')|json_encode|raw }},
        {#operationReporteValuations: {{ path('api_operation_reports_evaluation',  { 'year': ' ' })|json_encode|raw }},#}
        operationReporteValuations: {{ path('api_operation_reports_evaluation')|json_encode|raw }},
        operationReport: {
            getLastNumberFireDepartment: {{ path('api_operation_report_get_last_number_fire_department')|json_encode|raw }},
            getById: {{ path('api_operation_report_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_operation_report_new')|json_encode|raw }},
            edit: {{ path('api_operation_report_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_operation_report_delete', { 'id': ' ' })|json_encode|raw }}
        },
        operationReportCaches: {{ path('api_operation_report_caches')|json_encode|raw }},
        operationReportCache: {
            getById: {{ path('api_operation_report_cache_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_operation_report_cache_new')|json_encode|raw }},
            edit: {{ path('api_operation_report_cache_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_operation_report_cache_delete', { 'id': ' ' })|json_encode|raw }}
        },
        feedbacks: {{ path('api_feedbacks')|json_encode|raw }},
        feedback: {
            getById: {{ path('api_feedback_get_by_id',  { 'id': ' ' })|json_encode|raw }},
            new: {{ path('api_feedback_new')|json_encode|raw }},
            edit: {{ path('api_feedback_edit',  { 'id': ' ' })|json_encode|raw }},
            delete: {{ path('api_feedback_delete', { 'id': ' ' })|json_encode|raw }}
        },
    }
</script>

web-app/templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ encore_entry_link_tags('main') }}
{% endblock %}

{% block body %}

    <div id="app"></div>

    {% include 'main/api.html.twig' %}
    {% include 'main/translation.html.twig' %}
    {% include 'main/user.html.twig' %}

{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('main') }}
{% endblock %}

web-app/templates/main/translation.html.twig
{% include 'main/translation/components.html.twig' %}
{% include 'main/translation/confirmDialog.html.twig' %}
{% include 'main/translation/dataTables.html.twig' %}
{% include 'main/translation/dialogs.html.twig' %}
{% include 'main/translation/generals.html.twig' %}
{% include 'main/translation/menus.html.twig' %}
{% include 'main/translation/security.html.twig' %}
{% include 'main/translation/sites.html.twig' %}

web-app/templates/main/user.html.twig
<script>
    {% if app.user != null %}

    {# Nutzer Informatione #}
    const __LOGGED_USER__ = {
        id: {{ app.user.id|json_encode|raw }},
        email: {{ app.user.email|json_encode|raw }},
        firstname: {{ app.user.firstname|json_encode|raw }},
        isLoggedIn: {{ app.user.loggedIn|json_encode|raw }},
        surname: {{ app.user.surname|json_encode|raw }},
        roles: {{ app.user.roles|json_encode|raw }},
        rolesInherited: {{  get_inherited_roles()|json_encode|raw  }},
        myAlertAddresses: {{ app.user.myAlertAddresses|json_encode|raw }},
        myAlertAddressesComplete: {{ app.user.myAlertAddresses|json_encode|raw }},
        federalState: {
            id: {{ app.user.federalState.id|json_encode|raw }}
        },
        department: {
            id: {{ app.user.department.id|json_encode|raw }},
        },
        developerMode: {{ app.debug|json_encode|raw }}
    };

    {% else %}

    {# Nutzer Informatione #}
    const __LOGGED_USER__ = {
        id: "",
        email: "",
        firstname: "",
        isLoggedIn: false,
        surname: "",
        roles: "",
        rolesInherited: "",
        myAlertAddresses: "",
        myAlertAddressesComplete: "",
        federalState: {
            id: ''
        },
        department: {
            id: ''
        },
        developerMode: false
    };
    {% endif %}
</script>